language: c
compiler:
  - gcc
  - clang
# Change this to your needs
before_script:
  - cd $TRAVIS_BUILD_DIR/..
  - mkdir build && cd build
  - cmake -DBUILD_STATIC=OFF -DUSE_GCOV=ON -DCMAKE_INSTALL_PREFIX=$TRAVIS_BUILD_DIR/../install $TRAVIS_BUILD_DIR
script:
  - make
  - make check
  - if [[ "$CC" == "gcc" ]]; then
      make coverage;
      bash <(curl -s https://codecov.io/bash) -f coverage.info -R $TRAVIS_BUILD_DIR -X gcov;
    fi

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y locales cmake pkg-config libyajl-dev gettext valgrind icc-profiles-free lcov
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "nQH5wZmBXI/66hObgHN0/Nn2R8cI0rWvqkILNJH/ZpH0b0zVrbtsJ8DHp+EJKVvLonnEpWk729V+pCC2znqZKiyUnYnty6zy6AwZEHsOU5XY4f8O8wKgDqNf10if+oj/dcgjhthoX8tFmcW6axOtDwSFBpf9eP0GDUir2fhhns/dhagtKAAuaE9ojHWd9Rn04I1SLPfyql6WIgkO3Xxgp140jXkTfimKsnKxpmHYgoHT4MrFhpRaedCcRQVT7pO7qSZkyfqRYyCmplNCFu5/LCLqaWHhSDb2GFMWJfaCUX7+8mtbu77sLnR57UplPWhEyDhLHKd+m3MrE2Jg0c5VV4GzISdZgXvFaO4HVBF8VFBDrfe+vtzi8zbkFiC3H7TEeO5ezmI4RmE73Lsgx32JFfUybBo1vdX+pB1Lojjsv3QSwVowIr4Q6VjrYJk1kzIAdDG1OQivGk/GvJ8RRAHMEZlfCdXtQbnUOerzIucT8HtGdoT4i8nczw6tjrA2zbtdm4YjpR9T/x0XXweWmyBzvKSa4onsQDSOPamUVkJKGJAycqQC85wl/eTJoDJollGHvpo1oQR+yAc1l2Wpw9KrUFwS4QfoHgsBAjPVPMqNVy0b6H2xNliDGy9GgbKGEqJYnLTE84bOWUyDS0kaaNxZ5RYHpb0uIL/Ewo6li+x+b9s="

addons:
  coverity_scan:
    project:
      name: "OpenICC/config"
      description: "Build submitted via Travis CI"
    notification_email: ku.b@gmx.de
    build_command_prepend: "cd $TRAVIS_BUILD_DIR/..; mkdir build; cd build; cmake -DBUILD_STATIC=OFF -DUSE_GCOV=ON -DCMAKE_INSTALL_PREFIX=$TRAVIS_BUILD_DIR/../install $TRAVIS_BUILD_DIR; make clean"
    build_command:   "make -j 4"
    branch_pattern: master
