language: c
compiler:
  - gcc
  - clang
# Change this to your needs
before_script:
  - cd $TRAVIS_BUILD_DIR/..
  - mkdir build && cd build
  - cmake -DBUILD_STATIC=OFF -DCMAKE_INSTALL_PREFIX=$TRAVIS_BUILD_DIR/../install $TRAVIS_BUILD_DIR
script:
  - make
  - make check
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y locales cmake pkg-config libyajl-dev gettext

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "OmR8kvQ6hYSJBe3vDMFgB288MVe6ENAKzY58m2lFACLvSEYdrt1Nyh8fKrBT+uu2CBtAzmurbMbP/BBBJn3Rr6UsVf8N8Mg1D+qc0v0Jbk+jqWONx+dwLh/2ImPf5X825QEl7TvjFAAiGhhLdYhR6PBKT+pdN5X33GElzhvBR48="

addons:
  coverity_scan:
    project:
      name: "OpenICC/config"
      description: "Build submitted via Travis CI"
    notification_email: ku.b@gmx.de
    build_command_prepend: "./configure; make clean"
    build_command:   "make -j 4"
    branch_pattern: master
