language: c
compiler:
  - gcc
  - clang
# Change this to your needs
before_script:
  - cd $TRAVIS_BUILD_DIR/..
  - mkdir build && cd build
  - cmake -DBUILD_STATIC=OFF -DUSE_GCOV=ON -DCMAKE_INSTALL_PREFIX=$TRAVIS_BUILD_DIR/../install $TRAVIS_BUILD_DIR
script:
  - echo $PWD
  - ls ..
  - make
  - make check
  - if [[ "$CC" == "gcc" ]]; then
      make coverage;
      echo ls && ls;
      echo ls TRAVIS_BUILD_DIR && ls $TRAVIS_BUILD_DIR;
      echo ls TRAVIS_BUILD_DIR/build/ && ls $TRAVIS_BUILD_DIR/build/
      bash <(curl -s https://codecov.io/bash);
      bash <(curl -s https://codecov.io/bash) -G "-o src/ src/*.c";
      bash <(curl -s https://codecov.io/bash) -G "-o ../config/src/ ../config/src/*.c";
      bash <(curl -s https://codecov.io/bash) -G "-o src/libopenicc/ src/libopenicc/*.c";
      bash <(curl -s https://codecov.io/bash) -f coverage.info -R $TRAVIS_BUILD_DIR -X gcov;
    fi

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y locales cmake pkg-config libyajl-dev gettext valgrind icc-profiles-free lcov
