language: c
compiler:
  - gcc
  - clang
# Change this to your needs
before_script:
  - cd $TRAVIS_BUILD_DIR/..
  - mkdir build && cd build
  - echo $PWD
  - cmake -DBUILD_STATIC=OFF -DCMAKE_INSTALL_PREFIX=$TRAVIS_BUILD_DIR/../install $TRAVIS_BUILD_DIR
script:
  - make
  - echo $PWD
  - make check
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y locales cmake pkg-config libyajl-dev gettext valgrind icc-profiles-free
